### PR TITLE
Johnfreeman/issue127 combine setup scripts

### PR DESCRIPTION
**Pull request by jcfreeman2**
With this PR, the following has occurred:
* The responsibility of sourcing `dbt-setup-build-environment.sh` has now been completely assumed by the script formerly known as `dbt-setup-runtime-environment.sh`; running `dbt-setup-build-environment` from the command line is now deprecated
* The new name for `dbt-setup-runtime-environment.sh` is `dbt-refresh-work-env.sh`, though to run it one simply types `dbt-refresh-work-env`
* All changes are reflected in updates to the documentation

### CODE REVIEW

**Comment by alessandrothea** [comment]
Preliminary question: does it make sense to keep `dbt-setup-build-environment.sh` as a separate script?

**Comment by jcfreeman2** [comment]
After feedback from Alessandro and Pengfei, here's what we have:
* After sourcing `dbt-setup-env.sh` and cd'ing into (or `dbt-create.sh`ing) a work area, the user should run `dbt-workarea-env` before attempting to build anything; this replaces `dbt-setup-build-environment`
* In order to add applications, etc. from newly built repos, the user should run `dbt-workarea-env --refresh`; this replaces `dbt-setup-runtime-environment`

**Review by dingp — APPROVED** [review]
LGTM

**Comment by dingp** [comment]
My test succeeded with the following:

```bash=
source daq-buildtools/dbt-setup-env.sh
dbt-create.sh -n -l
dbt-create.sh -n last_successful n4
cd n4/ 
dbt-setup-build-environment
# [root@d7f3944b70ac n4]# dbt-setup-build-environment
# This command is deprecated; please run "dbt-workarea-env" instead

dbt-workarea-env
cd sourcecode/
git clone https://github.com/DUNE-DAQ/cmdlib
dbt-build.sh --install

dbt-workarea-env
# ERROR: [05/13/21 19:24:34] [dbt-workarea-env.sh]:  This script has already been sourced (successfully) in this shell; to source it again please pass it the "--refresh" argument. Returning...

dbt-workarea-env --refresh # success
```

**Comment by dingp** [comment]
One suggestion, instead of doing ` echo "This command is deprecated; please run \"dbt-workarea-env\" instead" >&2 ;` in `dbt-setup-build-environment()`, how about using `error` function defined in `scripts/dbt-setup-tools.sh`?

This will make the messaged colored in red.

**Pull request merged**
