### PR TITLE
Johnfreeman/update python vs bash disclaimers

### PR DESCRIPTION
**Pull request by jcfreeman2**
Improve the in-script messaging re: Bash vs. Python

### CODE REVIEW

**Comment by jcfreeman2** [comment]
Note also that on this branch there's a bugfix whereby the python function used to display the error message to the effect of "you didn't run `dbt-workarea-env`" is only available if you _did_ run `dbt-workarea-env`!

**Comment by dingp** [comment]
I found two differences between running the python version of `dbt-create` and the bash version.

Firstly, running `dbt-create.py` after `source daq-buildtools/env.sh` in a fresh shell, I got the error saying the no `python3` was found.
```
[root@92add70c204a scratch]# dbt-create.py -h
/usr/bin/env: python3: No such file or directory
```
So I did `source /cvmfs/dunedaq.opensciencegrid.org/products/setup; setup python`. And things worked out with that. It might  be nice to have a python version check and printout messages on setting up python3. In addition, I can have `python3` set up by default if using `setup_dbt` in `/cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh`.


Secondly, running `dbt-create.py` in a container where env `$USER` is not set, I got: 
```
ERROR: [01/18/22 23:00:10] [/scratch/daq-buildtools/bin/dbt-create.py:110]: Environment variable "USER" should be set. Try "export USER=$(whoami)"
``` 
This is not a real issue, but a new requirement to have "USER" env set in the docker image at the time of creating it. It was not necessary if using `dbt-create.sh` since it sets the ENV on the fly if necessary.

**Comment by jcfreeman2** [comment]
Good points, @pengfei. A few thoughts for you and @alessandrothea ; I'd like your input before I make edits:

Advantage of the current method of picking up python 3: `#!/bin/env python3` rather than `#!/bin/env python`:
* On systems where `python` defaults to v2, `python3` will pick up v3 python without any additional action needed

Disadvantages:
* The script won't work if the host doesn't have a `python3` command, even if `python` is, in fact, v3
* The error message `/usr/bin/env: python3: No such file or directory` isn't as clear as `Your "python" executable is v2, but you need v3`

If you think the advantage is outweighed by the disadvantages, I'll make the change Pengfei mentioned. 

Concerning the check in `dbt-create.*` for `USER` and `HOSTNAME` being set: these aren't, in fact, needed anywhere in daq-buildtools. They ARE, however, used when creating the `<package>_build_info.txt` files in daq-cmake, to create lines like:
```
user for build:         jcfree
hostname for build:     mu2edaq13
```
So we could move this check into the daq-cmake package, let me know what you think.

**Comment by dingp** [comment]
Could `daq-cmake` use the output of `whoami` if `USER` is not set? That will solve the issue.

Setting up python3 is not an issue if one uses dbt from cvmfs by using the `setup_dbt` function we provided. We can have python3 loaded first. However, if one uses dbt by checking it out locally, and sourcing `daq-buildtools/env.sh`, it would not be obvious about how to setup python3 with that error message. That's where my suggestion came from.

**Comment by jcfreeman2** [comment]
I've removed the requirements that HOSTNAME and USER be set and created a PR for daq-cmake where it now no longer uses those variables but instead uses the `hostname` and `whoami` commands; https://github.com/DUNE-DAQ/daq-cmake/pull/67

Concerning `python` vs. `python3`: what I've found is that if `python` is in fact v2, what happens when we have `#!/bin/env python` is that you get informed that `dbt-create.py` has a bunch of syntax errors, which makes sense given that Python 2 doesn't know about Python 3 syntax, libraries, etc.

**Comment by dingp** [comment]
Thanks! Using the output from the commands sounds great!

For the python version check, I am thinking that maybe something like the following is good enough.

```
#!/usr/bin/env python
import sys
if sys.version_info[0] < 3:
    raise Exception("Python 3 is required. If you have access to cvmfs, run this ... first.")

```

**Comment by jcfreeman2** [comment]
The issue with that is the check would never run if `python` were in fact v2. For example, on lxplus, where `python` is v2.7.5, if you have `#!/usr/bin/env python` at the top of `dbt-create.py` and then try running it, here's what happens:
```
[jofreema@lxplus714 public]$ dbt-create.py dunedaq-v2.9.0 daqbuild_deleteme
  File "/afs/cern.ch/work/j/jofreema/public/daq-buildtools/bin/dbt-create.py", line 5
    exec(open(f'{DBT_ROOT}/scripts/dbt_setup_constants.py').read())
                                                         ^
SyntaxError: invalid syntax
```

**Comment by dingp** [comment]
That error is caused by the usage of f-strings in the script. Python goes over the script for syntax error first before executing anything. Let me see if there's a better way to handle this except avoiding use the f-strings.

**Comment by dingp** [comment]
The only solution I found so far, is to have a wrapper script like the following, and put the current content of `dbt-create.py` into another file under `scripts` (without the shebang in the first line). This is demonstrated in the branch: [dingp/python_version_check_wrapper_for_dbt-create](https://github.com/DUNE-DAQ/daq-buildtools/tree/dingp/python_version_check_wrapper_for_dbt-create)

**Comment by dingp** [comment]
Found another issue with `sys.path.append(f'{PROD_BASEPATH}/dunedaq-v2.8.2/dbt-pyvenv/lib/python3.8/site-packages')` in the `dbt-create.py` script. This path is not guaranteed to exist, e.g. in docker images, or other systems where release 2.8.2 was not deployed.

https://github.com/DUNE-DAQ/daq-buildtools/blob/1e5e3b58818f4ff3c7474dd3826c3161661da3a0/bin/dbt-create.py#L8

If the path does not exist, then one would get the error saying `import sh failed, no module found`. It would be useful to add a existence check of the path and print messages saying this path is required upon failure.

**Comment by jcfreeman2** [comment]
Worth thinking about, but I think this PR has begun to accumulate various useful but unrelated topics which deserve their own Issues/PRs. This unnecessarily slows down the process of merging some already-approved items on its feature branch.

**Comment by dingp** [comment]
I assumed since this PR updated the disclaimer, it implied that we officially switch to the python version of `dbt-create.py`. If that's the case, it might be better to address these topics before we do the switch.

**Comment by jcfreeman2** [comment]
@alessandrothea right now in https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-buildtools/ I've instructed users to use not only `dbt-build.py` but also `dbt-create.py`; is this what we want, or should we ask users to run `dbt-build.py` when they build but stick with the traditional `dbt-create.sh` to set up an area?

**Comment by dingp** [comment]
`dbt-create.py -l` seems to list releases in random order.

```
 - N22-02-24
 - N22-02-05
 - N22-02-10-cs8
 - N22-03-01
 - N22-01-24
 - N22-01-28
 - N22-02-25
 - N22-01-11
 - N22-03-01-cs8
 - N22-01-21
 - N22-02-09
 - N22-01-02
 - N22-01-09
 - N21-12-27
 - N22-02-27-cs8
 - N22-02-26-cs8
 - N22-03-02-cs8
 - N22-01-25
 - N22-01-05
 - N22-02-23-cs8
 - N22-02-22-cs8
 - N22-01-23
[root@2f1c4a4289e7 scratch]# dbt-create.py -l
 - dunedaq-v2.2.0
 - dunedaq-v2.4.0
 - dunedaq-v2.8.0
 - dunedaq-v2.1.0
 - dunedaq-v2.8.1
 - dunedaq-v2.9.0
 - dunedaq-v2.7.0
 - dunedaq-v2.0.0
 - dunedaq-v2.3.0
 - dunedaq-v2.6.0
 - dunedaq-v2.8.2
 - dunedaq-v2.5.0
```

**Pull request merged**
