### PR TITLE
Add script to clone repos

### PR DESCRIPTION
**Pull request by jmcarcell**
This is a scrip to clone all the repositories that are not archived (by default, can be changed with `--archived`) to the current folder. Clones happen in parallel so this script runs in a few seconds. Useful to have the repos ready to work on them or grepping over all of them at the same time. Packages are chosen so it can be run out of a DUNEDAQ environment without installing anything.

### CODE REVIEW

**Comment by dingp** [comment]
To make it more useful, it would be good to have the script take the release YAML file from `daq-release/config/dunedaq-<release_name>` as an input, and checkout the tagged version (for frozen release) or develop head (the `dunedaq-develop` release), or commits used by a given nightly release (release YAML file for those can be found at `/cvmfs/dunedaq-development.opensciencegrid.org/spack-nightly/<NYY-MM-DD>/spack-repo/<NYY-MM-DD>.yaml`).

**Comment by dingp** [comment]
Currently there's a bash script ([`daq-release/scripts/checkout-package-release.sh`](https://github.com/DUNE-DAQ/daq-release/blob/develop/scripts/checkout-package-release.sh)) doing similar things. It takes the `release_manifest.sh` as input. This file was designed specifically for the UPS-based release. 

Since we are moving to Spack-based release, `release_manifest.sh` is going to be deprecated and replaced by the release YAML file. So we need to have an equivalent python tool to do similar things. 

The script in this PR is a very good starting point. 

[`daq-release/scripts/spack/make-release-repo.py`](https://github.com/DUNE-DAQ/daq-release/blob/develop/scripts/spack/make-release-repo.py) contains some code parsing the release YAML file. Adding similar code blocks to the script in this PR might be all we need.

**Comment by philiprodrigues** [comment]
For my use case, I have a long-lived directory containing all of the source repos, which I occasionally update, so it would be useful to have an option to `git pull` repositories that are already checked out, and `git clone` just the ones that don't exist already.

**Comment by jcfreeman2** [comment]
In a similar spirit, what if as part of the nightly build we also copied over the code used to perform the build? E.g., have directories like `/cvmfs/dunedaq-development.opensciencegrid.org/spack-nightly/N22-05-03/codebase/appfwk`, etc. In this case, without needing to download anything, users could see what installed code their own repos build against (in this case, assuming a `N22-05-03`-based workarea). 

We could even save paths like `/cvmfs/dunedaq-development.opensciencegrid.org/spack-nightly/N22-05-03/codebase` in an environment variable you could access from a work area, set in `dbt-workarea-constants.sh` - `DBT_UNDERLYING_CODEBASE`, something like that.

**Comment by dingp** [comment]
To prepare that `codebase` directory, technically, we do not need a home-brew script to get the source code of packages used in a release. Spack by default saves the archives of git repo into its local source cache. Examples can be found under `/cvmfs/dunedaq.opensciencegrid.org/spack-externals/spack-installation/var/spack/cache/_source-cache/git/DUNE-DAQ`. We can simply unroll all the tarballs under similar directories of a given release's spack instance before cleaning the caches.

**Comment by jcfreeman2** [comment]
Another idea I suggested at this morning's software coordination meeting: in a work area you could have softlinks to the code you were working with. If a package was checked out as a repo in `sourcecode/` the softlinks for that package would point there, otherwise it would point to relevant directory in `/cvmfs`, e.g. something like `/cvmfs/dunedaq-development.opensciencegrid.org/spack-nightly/N22-05-03/codebase`

We could just have a subdirectory in the work area which contains the links. Whenever `dbt-workarea-env` was run and the path environment variables were updated to reflect what repos are in `sourcecode/`, the links to the code could also be updated.

**Pull request closed without merging**
