### PR TITLE
Jcfreeman2/issue3 cmake wrapper functions

### PR DESCRIPTION
**Pull request by jcfreeman2**
This pull request is meant to be reviewed simultaneously with the appfwk pull request corresponding to its Issue #34, "Improve the single CMakeLists.txt file". Instructions for how to perform this simultaneous review can be found in the pull request comments for that appfwk issue.

### CODE REVIEW

**Comment by jcfreeman2** [comment]
Right now if a WG developer wants to add a package, they'd need to do the following:
-Clone their repo into the super project base directory (i.e., parallel to appfwk and ers)
-Add ups setups of any dependencies not already setup by the source_me_to_build script generated by quick-start.sh
-Add any additional logic needed to source_me_to_build. This would include, e.g., adding a source of their own version of setupForRunning.sh

Now, if we want to generate a global setupForRunning.sh, the question becomes how to implement it. This is an interesting question because if you're adding a new package, quick-start.sh isn't psychic and doesn't know what your package's name is, so it can't straightforwardly go into your package's directory tree to fish out your setupForRunning.sh. We could establish as a standard that if a group wants their package logic to be incorporated without them needing to manually edit source_me_to_build, then they could create (if it it doesn't exist) or append to (if it does) a setupForRunning.sh script which exists in the superproject base directory. Or we could have it create a separate script in the superproject base directory with a name like setupForRunning_<mypackage>.sh, and then source_me_to_build would loop on and source all setupForRunning_*.sh scripts. Or there may be other ways to do this. 

Alessandro, what's your preference?

**Comment by alessandrothea** [comment]
Ok, let's try to think this through.

the `setupForRunning` in `appfwk` is very straightforward

```sh
export PATH=@PATH_DIRS@:$PATH
export CET_PLUGIN_PATH=@LIB_DIRS@${CET_PLUGIN_PATH:+\:$CET_PLUGIN_PATH}
export LD_LIBRARY_PATH=@LIB_DIRS@${LD_LIBRARY_PATH:+\:$LD_LIBRARY_PATH}
```

DUNEDAQ packages are supposed to all have the same structure
```
appfwk/
|-- CMakeFiles
|-- apps
|-- scripts
|-- src
|-- test
`-- unittest
```
therefore it should not be difficult for the top-level CMakeList to generate the setup scripts for all `dunedaq` packages it's aware of. This requires a mechanism to declare that a package is a `dunedaq` package and a knwledge of cmake that I don't have.

**Comment by bieryAtFnal** [comment]
I'll confess that I'm not familiar with how setupForRunning.sh is being used now.  (Here's a really dumb question - how do I search for a string within a set of Github Wiki pages?  I can't tell if it's described somewhere.)

I can share a couple of ideas that I think would be nice/OK.

- I think that it would be great if there were some sort of top-level setupForRunning.sh script.  I don't have a preference whether it calls companion scripts in each of the repos that are included in the developer work area or not.

- as a user creating a new repo for a new set of DAQModules, I would be fine with adding the new repo/subdir to an existing top-level setupForRunning.sh script (if we say that the quick-start.sh script creates such a script initially).  I'll need to add my new subdir/repo to the top-level CMakeLists.txt file, so it doesn't seem like a big deal to also add it to a top-level setupForRunning.sh.  If however, something can be done automatically, that would be great, too.

**Comment by alessandrothea** [comment]
So a potential issue with the current `setupForRunning`, which is tuned on `apfwk`,  is that's generated by quickstart. 
Any hand-made change to include user repo settings would need to be reproduced every time a new area is created.

**Comment by dingp** [comment]
I am making a release manifest file which includes a list of packages, which then is read by QuickStart script. So the release manifest file will be the only place to change if we have a new package.

Best,
Pengfei

On Jun 18, 2020, at 11:06 AM, Alessandro Thea <notifications@github.com<mailto:notifications@github.com>> wrote:



So a potential issue with the current setupForRunning, which is tuned on apfwk, is that's generated by quickstart.
Any hand-made change to include user repo settings would need to be reproduced every time a new area is created.

**Pull request merged**
