### PR TITLE
JCF: Issue #219: allow the user to pass the name of an individual fil…

### LINKED ISSUE #219: The `--lint` argument should be able to accept a filename
Currently the `--lint` argument to `dbt-build` can either accept no arguments (in which case all the repos in `sourcecode/` are linted) or the name of one of the repos (in which case all the code in that repo, but only that repo, gets linted). An option which could provide more fine grained control while still being backwards-compatible would be to allow the user to pass the name of a specific source file to `--lint`. E.g.
```
dbt-build --lint sourcecode/iomanager/test/apps/queue_IO_check.cxx
```
would lint the code for the `queue_IO_check` queue performance test app in `iomanager` as opposed to _all_ the code in `iomanager`.

### PR DESCRIPTION
**Pull request by jcfreeman2**
…e to the --lint argument

### CODE REVIEW

**Review by dingp — COMMENTED** [review]
This PR works as described.

The following tests have been done:

1. `dbt-build --lint`;
2. `dbt-build --lint listrev`;
3. under `DBT_AREA_ROOT`, `dbt-build --lint sourcecode/listrev/plugins/ReversedListValidator.cpp`;
4. under `DBT_AREA_ROOT/sourcecode`, `dbt-build --lint sourcecode/listrev/plugins/ReversedListValidator.cpp`;
5. under `DBT_AREA_ROOT/sourcecode`, `dbt-build --lint listrev/plugins/ReversedListValidator.cpp`.

Tests 1-4 all succeeded as described by the documentation. Test 5 failed as that's not supported, but a developer might do that naturally (supplying a relative path to the current directory for the file to be lint). 

It might be good to support the relative path to current directory as well.

**Comment by jcfreeman2** [comment]
If we modify the code so test 5 works, I think it makes sense that test 4 should then fail; do you agree?

**Comment by dingp** [comment]
Sounds good to me!

**Comment by jcfreeman2** [comment]
Code has been modified s.t. now test 4 will fail and test 5 will pass.

**Comment by dingp** [comment]
Verified that test 4 fails and test 5 passes with the latest commit.

**Review by dingp — APPROVED** [review]

**Pull request merged**
