### PR TITLE
Feature/dingpf individual unittest log

### PR DESCRIPTION
**Pull request by dingp**
This PR changes `dbt-build.py`, so that:
* Unit test and linting log files are organized into sub-directories;
* A summary of unit test results is created at the end of all unit tests.

### CODE REVIEW

**Comment by jcfreeman2** [comment]
Ran some unit testing and linting and the saved results look good

**Comment by jcfreeman2** [comment]
One quick thing: it may be worth considering consistency between the filenames for individual unit tests vs. the summary. E.g., right now in a given subdirectory we have:
```
dfmodules_DataFlowOrchestrator_test_unittest_Fri_Mar_11_17_18_24_CST_2022.log
unit_test_summary.log
```
so it's worth considering whether both, or neither, of the filenames should bear the timestamp.

**Comment by dingp** [comment]
the timestamp is already in the directory name, so I consider removing it from the name of individual test logs.

**Comment by dingp** [comment]
similarly for the linting log, the `datestring` is included in the dir name, so removing it from the log file's name.

**Pull request merged**
