### PR TITLE
JCF: in light of the readout package's BufferedReadWrite test perform…

### PR DESCRIPTION
**Pull request by jcfreeman2**
…ing >10 million individual tests, suppress the output of successful tests

Level chosen based on the information contained in  https://www.boost.org/doc/libs/1_66_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/log_level.html

### CODE REVIEW

**Comment by eflumerf** [comment]
Maybe this should be settable via an environment variable?
`${DBT_LOG_LEVEL:-"test_suite"}`

**Comment by dingp** [comment]
https://www.boost.org/doc/libs/1_35_0/libs/test/doc/components/utf/parameters/log_level.html

Maybe `BOOST_TEST_LOG_LEVEL` env can help here.

**Review by dingp — COMMENTED** [review]
LGTM

**Comment by jcfreeman2** [comment]
In light of Eric's comment, Pengfei uncovered a Boost environment variable, `BOOST_TEST_LOG_LEVEL`, which controls the unit test output (see https://www.boost.org/doc/libs/1_35_0/libs/test/doc/components/utf/parameters/log_level.html). We've also received feedback users who prefer to keep the current default behavior of having successful tests print. However, if for a given package a unit test is performed several million times and its output is flooding the screen and slowing things down, the tester has two options:
* Set `BOOST_TEST_LOG_LEVEL` to a less verbose value, e.g., `export BOOST_TEST_LOG_LEVEL=test_suite`
* Write a small function which loops over the millions of tests and returns false if one of them fails, providing its return value to `BOOST_REQUIRE`

**Comment by eflumerf** [comment]
See also:
`https://github.com/DUNE-DAQ/readout/pull/71`
`https://github.com/DUNE-DAQ/dataformats/pull/56`
`https://github.com/DUNE-DAQ/appfwk/pull/166`

**Comment by floriangroetschla** [comment]
The main problem I faced was not that I could not run the tests because I was just using the executables directly. The problem I see is that other testers running the unittests for readout run into this issue and have to lower the log level themselves before they are able to complete them. Is there a recommended way to set the log level for just one package so that all tests can pass with the default script? The workaround to only call `BOOST_REQUIRE` if a test failed seems a bit hacky to me so I would really appreciate a way to set the log level for the readout package such that it works with the default configuration of the buildtools.

**Comment by roland-sipos** [comment]
We have something to discuss here @alessandrothea . Current PRs seem to have insufficient or weird "solutions" to lower verbosity.

**Pull request merged**
