### PR TITLE
Using pwd command to determine current working directory

### PR DESCRIPTION
**Pull request by alessandrothea**
Switched to using the shell `pwd` command to retrieve the current working directory when searching for the work area root folder in `find_work_area`

### CODE REVIEW

**Review by jcfreeman2 — COMMENTED** [review]
What I'm finding if I use this feature branch is that if `sourcecode` in the base of the work area is a symlink to `$HOME/sourcecode`, then `dbt-build` creates and populates a `build` and `log` in `$HOME` (so, e.g., we get `$HOME/log/build_attempt_Thu_Oct_10_11_02_23_AM_CDT_2024.log`). This, as opposed to it filling the `./log` and `./build` subdirectories of the work area itself. Is this intended?

**Comment by alessandrothea** [comment]
Unintended. Let me investigate.

**Comment by alessandrothea** [comment]
I think the cause was an extra newline character in the path returned by the `find_work_area` internal loop. That is fixed. Could you try again?

**Comment by jcfreeman2** [comment]
`./build` and `./log` are no longer being created at the same level; approved

**Review by jcfreeman2 — APPROVED** [review]
Works, as described in previous comment. Approved.

**Pull request merged**
