### PR TITLE
Jcfreeman2/issue68 more error checking

### PR DESCRIPTION
**Pull request by jcfreeman2**

### CODE REVIEW

**Review by alessandrothea — COMMENTED** [review]
Beside the comments to the code, trying to handle every possible error ses quite unpractical. Was using `set -e` considered for instance?

**Comment by jcfreeman2** [comment]
@alessandrothea Thanks for taking a look. To address your points:
* I'm happy to give error messages a standard format within scripts, and perhaps even between them as well.
* It's understandable that you raise an eyebrow at some of those error checks, e.g., seeing whether or the source of `setup_tools.sh` returns nonzero, given that it's simply a set of functions. My take on it is, if at some point someone (maybe not even one of us) decides it would be a cool idea to start actually executing code in there (or any other script which gets sourced) then the success or failure of that code won't be ignored
* Adding `set -e` sounds like a good idea. Personally I like writing out explicit error messages as it makes it clearer to the user where things went wrong, but as you allude to even with the best of intentions it's hard to explicitly handle all possible errors in a set of scripts. 
* I'm not an expert here, but if there's a 1 <=> 1 correspondence between `activate` succeeding and VIRTUAL_ENV being set to something then you're right that checking `activate`'s return value is redundant
* How about we replace`./build` with `"build"`?

**Comment by alessandrothea** [comment]
- Ok to converge on a standard error format. Shall we create a helper function in setup_tools to reduce the boilerplate?
- `setup_tools.sh` shall we just agree that it's a function/constant only script and no code shall be ever executed in there?
In general one could come up with a `source_and_check` fucntion to reduce the boilerplate, but that would reside in `setup_tools.sh` so it wouldn't be of help for this case. 
- OK, probably the optimum is somewhere in the middle. Custom
 error messages wherever possible and `set -e` to catch the rest (to be checked whether `set -e` or `trap ERRsomething`)
- I cannot see any other reason for the `VIRTUAL_ENV` check other than ensuring that activate was successful
- "build" it is
- no path checks 👍

**Comment by jcfreeman2** [comment]
Update, involving a statement and a question:

I've added a `log_error` function which will provide a standard format to error strings, e.g.:
```
ERROR: [12/04/20 10:17:55] [setup_build_environment.sh]: The "setup python " call failed. Returning...
```
...with the output going to stderr. Now: I'd been hoping that `log_error` could actually end the script by itself, relieving the developer of the need to "manually" add a return/exit call afterwards. This isn't a problem if `log_error` gets called from an executable script (e.g., `build_daq_software.sh`); we can just have it directly call `exit`. However, if we do that from a sourced script (e.g., `setup_build_environment.sh), that would actually log someone out of their terminal, which I think we can all agree isn't an acceptable result. So, we have a couple of options:

* Leave physical error handling to the caller of `log_error`, and have it assume the more modest role of providing a standard format to error messages, as is currently the case at the head of this PR's branch.

* Have `log_error` check to see if it's ultimately inside of an executed script or a sourced script, calling exit in the former case and doing nothing in the latter case. The disadvantage here is it means `log_error`'s callers would need to remember to handle errors in the case of sourced scripts.

**Comment by dingp** [comment]
> * I cannot see any other reason for the `VIRTUAL_ENV` check other than ensuring that activate was successful

The previous `setup_python_env.sh` script was designed to be used as `setup_build_environment`, and be present in a working directory. So the `VIRTUAL_ENV` check there was to ensure that a user does not source this script again if the env is already activated.

But since we are now using `create_env.sh` and by default, having the env activated, this check is no longer necessary.

**Comment by jcfreeman2** [comment]
I've renamed `log_error` as `error` and have it exit automatically if it's (ultimately) being called from an executable script (`quick-start.sh`, `build_daq_software.sh`) as opposed to one that's sourced (`setup_build_environment.sh`, `setup_runtime_environment.sh`). I've also made the error statement itself (as opposed to the date/script name preface) appear in red; this is a style choice, where alternatives would be to have the whole thing appear in red, or just the preface and not the statement itself.

**Comment by jcfreeman2** [comment]
A little while ago on Slack Alessandro asked if this was ready to merge; just did a double check of all the changes and looks good.

**Pull request merged**
