### PR TITLE
Add zmq to ups products (used by IPM)

### PR DESCRIPTION
**Pull request by philiprodrigues**
The upcoming IPM library uses the zmq product from the dunedaq cvmfs area, so this PR adds zmq to the list of ups products set up in a new working area.

### CODE REVIEW

**Comment by brettviren** [comment]
I don't know how to check if this may already be in place but if cppzmq's `zmq::poller` is to be used we need to build libzmq with draft support.  This will also give us access to thread-safe socket types. 

It is done by adding a flag to libzmq's `configure`:

```
./configure --prefix=${PREFIX} --enable-drafts
```

We'll also need to preface how we include cppzmq's header's.  To make it foolproof, I'd suggest a single header entry point, eg `ipm/zeromq.hpp` holding:

```c++
#define ZMQ_BUILD_DRAFT_API 1
#include <zmq.hpp>
#include <zmq_addon.hpp>
```

Then, the IPM source files which currently or in the future might `#include <zmq.hpp>` should instead `#include "ipm/zeromq.hpp"` to assure a properly configured API.

**Comment by dingp** [comment]
The version published in cvmfs is from SciSoft which did not use `--enable-drafts`.

I can make a new one `v4_3_1b` with that option enabled later this morning.

**Comment by dingp** [comment]
Published zmq `v4_3_1b` to cvmfs. This is the version with `--enable-drafts` turned on.

@philiprodrigues Could you please update your PR with this version of `zmq` ?

**Comment by philiprodrigues** [comment]
Thanks @dingp, I've updated to v4_3_1b

**Comment by dingp** [comment]
@philiprodrigues  @eflumerf @brettviren Alessandro pointed out that I should have put a new package in products_dev first until it becomes part of the release. So I moved it from products to products_dev just now. You many need to set up that products area additionally if you are not doing so already.

**Comment by philiprodrigues** [comment]
I object to this change, and to reverting my PR without discussion. IPM is an official and core part of the DAQ software and not some personal side project. Users have to be able to build it without extra manual changes. Please include zmq in the official UPS area.

**Comment by alessandrothea** [comment]
Sorry for the lack of appropriate discussion before reverting the PR. It should not have been approved in the first place (misunderstanding between me and @dingp) and we were in the v2 release endgame, which was the priority.

Ipm is indeed a core package as it should be possible setting up a development area with as little manual changes as possible, ideally zero. Alas we are not quite there yet. 

The ups package list has to be factorised from `daq-buildtools` and the inclusion of Dec products made easier. This is something @dingp got started on a while back, that was put on back-burner and should now be resumed.

Also, the organisation of the cvmfs area is being revised. Adding new packages to the `products` area while this process is ongoing can cause unnecessary distractions which is why we have the `products_dev` staging area.

I understand that this is not optimal, on the other hand the manual changes required to add new dev products to a work area are minimal, which should make the discomfort caused by hem bearable for a little longer while we work out abetter solution.

**Pull request merged**
